# Use postgres/example user/password credentials
version: '3.1'

services:

  dynamodb:
    image: amazon/dynamodb-local
    restart: always
    container_name: dynamodb-local
    ports:
      - 8000:8000
    networks:
      bridge:

networks:
  bridge:
